const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{can_dash: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Timer: 0},
	{Hero: 0},
	{Solid: 0},
	{TiledBackground2: 0},
	{Keyboard: 0},
	{TiledBackground3: 0},
	{Group: 0},
	{DeathPit: 0},
	{Sprite2: 0},
	{Group2: 0},
	{right: 0},
	{Pathfinding: 0},
	{Enemy: 0},
	{Sprite: 0},
	{TiledBackground5: 0},
	{Sprite3: 0},
	{TiledBackground4: 0},
	{Sprite4: 0},
	{TiledBackground6: 0},
	{Sprite5: 0},
	{Button: 0},
	{Group3: 0},
	{Sprite6: 0},
	{Mouse: 0},
	{Group4: 0},
	{TiledBackground7: 0},
	{Sprite7: 0},
	{Sine: 0},
	{Sprite8: 0},
	{TiledBackground8: 0},
	{Sprite9: 0},
	{TiledBackground9: 0},
	{TiledBackground10: 0},
	{Group5: 0},
	{Group6: 0},
	{Group7: 0},
	{Group8: 0},
	{Group9: 0},
	{INTRO1VER: 0},
	{INTRO1VER2: 0},
	{INTRO1VER3: 0},
	{INTRO1VER4: 0},
	{INTRO1VER5: 0},
	{INTRO1VER6: 0},
	{INTRO1VER7: 0},
	{INTRO1VER8: 0},
	{INTRO1VER9: 0},
	{INTRO1VER10: 0},
	{INTRO1VER11: 0},
	{ButtonNext: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{INTRO1VER12: 0},
	{INTRO1VER13: 0},
	{INTRO1VER14: 0},
	{INTRO1VER15: 0},
	{INTRO1VER16: 0},
	{INTRO1VER17: 0},
	{INTRO1VER18: 0},
	{INTRO1VER19: 0},
	{INTRO1VER20: 0},
	{INTRO1VER21: 0},
	{INTRO1VER22: 0},
	{INTRO1VER23: 0},
	{Frame: 0},
	{INTRO2VER: 0},
	{INTRO2VER2: 0},
	{INTRO2VER3: 0},
	{INTRO2VER4: 0},
	{INTRO2VER5: 0},
	{INTRO2VER6: 0},
	{INTRO2VER7: 0},
	{INTRO2VER8: 0},
	{INTRO3VER: 0},
	{INTRO3VER2: 0},
	{INTRO3VER3: 0},
	{INTRO3VER4: 0},
	{INTRO3VER5: 0},
	{INTRO3VER6: 0},
	{HomeScreen: 0},
	{Sprite12: 0},
	{HomeScreen2: 0},
	{Sprite13: 0},
	{HomeScreen3: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{INTRO2VER9: 0},
	{INTRO4VER: 0},
	{INTRO4VER2: 0},
	{INTRO4VER3: 0},
	{INTRO4VER4: 0},
	{INTRO4VER5: 0},
	{INTRO4VER6: 0},
	{INTRO4VER7: 0},
	{Touch: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Hero: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Group: class extends self.ISpriteInstance {},
	DeathPit: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Group2: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Group3: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Group4: class extends self.ISpriteInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	Group5: class extends self.ISpriteInstance {},
	Group6: class extends self.ISpriteInstance {},
	Group7: class extends self.ISpriteInstance {},
	Group8: class extends self.ISpriteInstance {},
	Group9: class extends self.ISpriteInstance {},
	INTRO1VER: class extends self.ISpriteInstance {},
	INTRO1VER2: class extends self.ISpriteInstance {},
	INTRO1VER3: class extends self.ISpriteInstance {},
	INTRO1VER4: class extends self.ISpriteInstance {},
	INTRO1VER5: class extends self.ISpriteInstance {},
	INTRO1VER6: class extends self.ISpriteInstance {},
	INTRO1VER7: class extends self.ISpriteInstance {},
	INTRO1VER8: class extends self.ISpriteInstance {},
	INTRO1VER9: class extends self.ISpriteInstance {},
	INTRO1VER10: class extends self.ISpriteInstance {},
	INTRO1VER11: class extends self.ISpriteInstance {},
	ButtonNext: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	INTRO1VER12: class extends self.ISpriteInstance {},
	INTRO1VER13: class extends self.ISpriteInstance {},
	INTRO1VER14: class extends self.ISpriteInstance {},
	INTRO1VER15: class extends self.ISpriteInstance {},
	INTRO1VER16: class extends self.ISpriteInstance {},
	INTRO1VER17: class extends self.ISpriteInstance {},
	INTRO1VER18: class extends self.ISpriteInstance {},
	INTRO1VER19: class extends self.ISpriteInstance {},
	INTRO1VER20: class extends self.ISpriteInstance {},
	INTRO1VER21: class extends self.ISpriteInstance {},
	INTRO1VER22: class extends self.ISpriteInstance {},
	INTRO1VER23: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	INTRO2VER: class extends self.ISpriteInstance {},
	INTRO2VER2: class extends self.ISpriteInstance {},
	INTRO2VER3: class extends self.ISpriteInstance {},
	INTRO2VER4: class extends self.ISpriteInstance {},
	INTRO2VER5: class extends self.ISpriteInstance {},
	INTRO2VER6: class extends self.ISpriteInstance {},
	INTRO2VER7: class extends self.ISpriteInstance {},
	INTRO2VER8: class extends self.ISpriteInstance {},
	INTRO3VER: class extends self.ISpriteInstance {},
	INTRO3VER2: class extends self.ISpriteInstance {},
	INTRO3VER3: class extends self.ISpriteInstance {},
	INTRO3VER4: class extends self.ISpriteInstance {},
	INTRO3VER5: class extends self.ISpriteInstance {},
	INTRO3VER6: class extends self.ISpriteInstance {},
	HomeScreen: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	HomeScreen2: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	HomeScreen3: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	INTRO2VER9: class extends self.ISpriteInstance {},
	INTRO4VER: class extends self.ISpriteInstance {},
	INTRO4VER2: class extends self.ISpriteInstance {},
	INTRO4VER3: class extends self.ISpriteInstance {},
	INTRO4VER4: class extends self.ISpriteInstance {},
	INTRO4VER5: class extends self.ISpriteInstance {},
	INTRO4VER6: class extends self.ISpriteInstance {},
	INTRO4VER7: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {}
}